### PR TITLE
Signal keyconfig problem

### LINKED ISSUE #152: Payjoin-cli V2 returns uninstructive 400 from OHTTP relay when client ohttp_config mismatches gateway
Working through the [payjoin-cli](https://github.com/payjoin/rust-payjoin/tree/master/payjoin-cli#manual-end-to-end-regtest-testing) sample docs, I ran into an error when trying to generate a BIP-21 receive URI:

```
payjoin-cli receive 100
Error: HTTP request failed

Caused by:
    https://ohttp-relay.obscuravpn.io/payjoin: status code 400
```

My config.toml:
```
bitcoind_cookie="/Users/brandonlucas/Library/Application Support/Bitcoin/regtest"
bitcoind_rpchost="http://localhost:18443/wallet/alice"
pj_endpoint="https://payjo.in"
ohttp_config="AQAgQB9BwO5taMV6Skp4dl9HpFPw5SNUnnd-imKkUm8P5EIABAABAAM"
ohttp_proxy="https://ohttp-relay.obscuravpn.io/payjoin"
```

The `alice` wallet has UTXOs ready to spend from, this is all on regtest.

### PR DESCRIPTION
**Pull request by DanGould**
Fix #152 

Signal OHTTP Key Configuration problem

Respond with `application/problem+json` when OHTTP decapsulation fails
according to draft-ietf-ohai-ohttp section 5.3. See:
https://ietf-wg-ohai.github.io/oblivious-http/draft-ietf-ohai-ohttp.html#section-5.3

Ensure the error response is clearly understood in payjoin-cli

### CODE REVIEW

File: payjoin-relay/src/main.rs [hunk 1]
```diff
@@ -218,6 +221,15 @@ impl HandlerError {
                 error!("Internal server error: {}", e);
                 *res.status_mut() = StatusCode::INTERNAL_SERVER_ERROR
             }
+            HandlerError::OhttpKeyRejection(e) => {
+                const OHTTP_KEY_REJECTION_RES_JSON: &str = r#"{"type":"https://iana.org/assignments/http-problem-types#ohttp-key", "title": "key identifier unknown"}"#;
```
Comment (jbesraa) [inline payjoin-relay/src/main.rs:225]: i think the title is a bit opaque, maybe its worth mentioning the specific problematic param ie `ohttp_config`

**Review by jbesraa — APPROVED** [review]

File: payjoin-relay/src/main.rs (hunk 1 above)
Comment (DanGould) [reply payjoin-relay/src/main.rs:225]: I agree, it would be instructive to show something like "Key identifier unknown. Refresh your payjoin directory configuration at $OHTTP_GATEWAY/ohttp-config" or similar.

I think this is a separate task for payjoin-cli, and eventually an implementation library doing I/O.
