### PR TITLE
Use tempfile for temporary e2e test directories

### LINKED ISSUE #859: inconsistent concurrent test run  due to using global temporary directory
e2e.rs uses env::temp_dir, which typically resolves to a shared directory like /tmp/ on POSIX systems. If two end-to-end tests run concurrently, they may end up using the same temporary path. This poses a risk of test interference—multiple tests operating on the same temp directory can lead to flaky behavior and hard-to-reproduce bugs.

Additionally, this can cause issues with CleanupGuard, which may silently fail if two instances race to perform cleanup.

### PR DESCRIPTION
**Pull request by spacebear21**
`tempfile::tempdir()` ensures that each test operates in an independent directory, preventing contention between concurrent tests.

Closes #859

### CODE REVIEW

**Comment by Johnosezele** [comment]
ACK [f4722de](https://github.com/payjoin/rust-payjoin/pull/868/commits/f4722deada16a9c02f8b39c97edc789ce420afef). I built and ran the e2e tests concurrently. The v1 test now passes consistently, which confirms the fix for the file-locking race condition. I am aware of the v2 test failure, but understand it is an unrelated issue. I agree this can be merged.

<details><summary>Reproducing the Issue on master</summary>
<p>

To begin, I checked out the master branch to confirm the original problem. I ran the end-to-end tests in parallel with the following command:

```bash
cargo test --test e2e --features _danger-local-https,v1,v2 -- --test-threads=8
```

This successfully reproduced the issue. The tests failed with file-locking errors due to the race condition, as expected:

```txt
running 2 tests
Error: Database operation failed: IO error: could not acquire lock on "/var/folders/.../receiver_db/db": Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }
...
test e2e::send_receive_payjoin_v1 ... FAILED
test e2e::send_receive_payjoin_v2 ... FAILED

failures:
    e2e::send_receive_payjoin_v1
    e2e::send_receive_payjoin_v2

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out;
```

</p>
</details>


<details><summary>Verifying the Fix on the PR Branch</summary>
<p>

Next, I checked out this pull request branch (pr-868) and ran the exact same command to verify the fix:

```bash
cargo test --test e2e --features _danger-local-https,v1,v2 -- --test-threads=8
```

With these changes, the v1 test now passes consistently, demonstrating that the file-locking race condition has been resolved. The output was as follows:

```txt
running 2 tests
...
test e2e::send_receive_payjoin_v1 ... ok
test e2e::send_receive_payjoin_v2 ... FAILED
...

failures:

---- e2e::send_receive_payjoin_v2 stdout ----
Database running on 127.0.0.1:55001
Directory server binding to port [::]:60819
OHTTP relay binding to port [::]:60820
2025-07-11T13:30:48.543147Z ERROR payjoin_directory: TLS accept error: received fatal alert: DecryptError
2025-07-11T13:30:48.545147Z ERROR payjoin_directory: TLS accept error: received fatal alert: DecryptError

thread 'e2e::send_receive_payjoin_v2' panicked at payjoin-cli/tests/e2e.rs:314:13:
Fallback send was not detected
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    e2e::send_receive_payjoin_v2

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out;
```

I noted that the `send_receive_payjoin_v2` test still fails, but as you mentioned, this is due to an unrelated TLS issue stemming from changes in PR [#869](https://github.com/payjoin/rust-payjoin/pull/869).

</p>
</details>

File: payjoin-cli/tests/e2e.rs [hunk 1]
```diff
@@ -157,41 +140,33 @@ mod e2e {
...
         type Result<T> = std::result::Result<T, BoxError>;
 
         init_tracing();
         let mut services = TestServices::initialize().await?;
-        let temp_dir = env::temp_dir();
-        let receiver_db_path = temp_dir.join("receiver_db");
-        let sender_db_path = temp_dir.join("sender_db");
-        let _cleanup_guard =
-            CleanupGuard { paths: vec![receiver_db_path.clone(), sender_db_path.clone()] };
+        let temp_dir = tempdir()?;
```
Comment (nothingmuch) [inline payjoin-cli/tests/e2e.rs:151]: The docs say:

> Note that if the program exits before the TempDir destructor is run, such as via [std::process::exit()](http://doc.rust-lang.org/std/process/fn.exit.html), by segfaulting, or by receiving a signal like SIGINT, then the temporary directory will not be deleted.

i would bet `cargo test` SIGINT has a handler that does something smarter, do you know if this is the case?

For debugging we should probably also have something like this:

```suggestion
        // FIXME parse the var as truthy don't just check is_ok()
        let disable_cleanup = env::var("KEEP_TEMPDIR").is_ok();
        let temp_dir = Builder::new().disable_cleanup(disable_cleanup).tempdir()?;
```

Comment (spacebear21) [reply payjoin-cli/tests/e2e.rs:151]: I'm not aware of any special SIGINT handling by `cargo test`, but IMO not deleting temp files on sigint is no big deal, since each tempdir is unique it's unlikely there would ever be a conflict from a previous interrupted test run.
