### PR TITLE
Fix rpc-error due to quick transaction lookup

### LINKED ISSUE #1154: payjoin-cli receiver returns a 500 error after a successful payjoin.
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which crate is this issue for?

payjoin-cli

### How did you obtain this crate?

Compiled from source

### What version of the selected crate are you using?

payjoin 1.0.0-rc

### Current behavior

The cli receiver returns a 500 internal server error possibly related to the bitcoind error pointed out in the discord

> i think it is a bitcoin rpc error: https://github.com/alpenlabs/bitcoind-async-client/blob/2f3f655d212202babc39e73d5a25c41a631a792a/src/error.rs#L40
[11:46 AM]
> not the most helpful display representation... can you check your bitcoind logs?

### Expected behavior

The receiver should stop polling gracefully once a payjoin is completed.

### Steps to reproduce

complete a payjoin-cli v2-to-v2 send receive flow

### Relevant log output

```
...
Response successful. Watch mempool for successful Payjoin. TXID: 872fec8edc0e63c925c9251687d54e4237
b676a6d0586ba4b03eb3a808928592
Error: Transient error: Implementation error: Obtained failure status(500): Internal Server Error

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anyhow-1.0.99/src/b
acktrace.rs:27:14
   1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::c
onvert::Infallible,E>>>::from_residual
             at /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust
/library/core/src/result.rs:2174:27
   2: payjoin_cli::app::v2::App::monitor_payjoin_proposal::{{closure}}
             at /home/user/Documents/Coding/Projects/rust-payjoin/payjoin-cli/src/app/v2/mod.rs:741
:17
   3: payjoin_cli::app::v2::App::send_payjoin_proposal::{{closure}}
             at /home/user/Documents/Coding/Projects/rust-payjoin/payjoin-cli/src/app/v2/mod.rs:732
:66
   4: payjoin_cli::app::v2::App::finalize_proposal::{{closure}}
             at /home/user/Documents/Coding/Projects/rust-payjoin/payjoin-cli/src/app/v2/mod.rs:713
:57
   5: payjoin_cli::app::v2::App::apply_fee_range::{{closure}}
             at /home/user/Documents/Coding/Projects/rust-payjoin/payjoin-cli/src/app/v2/mod.rs:697
:53
   6: payjoin_cli::app::v2::App::contribute_inputs::{{closure}}
             at /home/user/Documents/Coding/Projects/rust-payjoin/payjoin-cli/src/app/v2/mod.rs:688
:51
   7: payjoin_cli::app::v2::App::commit_outputs::{{closure}}
             at /home/user/Documents/Coding/Projects/rust-payjoin/payjoin-cli/src/app/v2/mod.rs:674
:53
   8: payjoin_cli::app::v2::App::identify_receiver_outputs::{{closure}}
             at /home/user/Documents/Coding/Projects/rust-payjoin/payjoin-cli/src/app/v2/mod.rs:665
:50
   9: payjoin_cli::app::v2::App::check_no_inputs_seen_before::{{closure}}
             at /home/user/Documents/Coding/Projects/rust-payjoin/payjoin-cli/src/app/v2/mod.rs:649
:61
  10: payjoin_cli::app::v2::App::check_inputs_not_owned::{{closure}}
             at /home/user/Documents/Coding/Projects/rust-payjoin/payjoin-cli/src/app/v2/mod.rs:636
:63
  11: payjoin_cli::app::v2::App::check_proposal::{{closure}}
             at /home/user/Documents/Coding/Projects/rust-payjoin/payjoin-cli/src/app/v2/mod.rs:620
:58
  12: payjoin_cli::app::v2::App::read_from_directory::{{closure}}
             at /home/user/Documents/Coding/Projects/rust-payjoin/payjoin-cli/src/app/v2/mod.rs:601
:50
  13: payjoin_cli::app::v2::App::process_receiver_session::{{closure}}
             at /home/user/Documents/Coding/Projects/rust-payjoin/payjoin-cli/src/app/v2/mod.rs:558
:67
  14: <payjoin_cli::app::v2::App as payjoin_cli::app::App>::receive_payjoin::{{closure}}
             at /home/user/Documents/Coding/Projects/rust-payjoin/payjoin-cli/src/app/v2/mod.rs:274
:14
  15: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust
/library/core/src/future/future.rs:133:9
  16: payjoin_cli::main::{{closure}}
```

### Operating system and version

NixOS 25.05

### PR DESCRIPTION
**Pull request by zealsham**
This pr addresses an error that occurs due to rpc client looking up the transaction right before it's on chain . Error: Transient error: Implementation error: Obtained failure status(500): Internal Server Error

The delay introduced allows the transaction to broadcasted on chain before the lookup

This closes #1154 

<details>
  <summary>Pull Request Checklist</summary>

Please confirm the following before requesting review:

- [x] I have [disclosed my use of
  AI](https://github.com/payjoin/rust-payjoin/blob/master/.github/CONTRIBUTING.md#ai-assistance-notice)
  in the body of this PR.
- [x] I have read [CONTRIBUTING.md](https://github.com/payjoin/rust-payjoin/blob/master/.github/CONTRIBUTING.md#commits) and **rebased my branch to produce [hygienic commits](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#committing-patches)**.
</details>

### CODE REVIEW

File: payjoin-cli/src/app/v2/mod.rs [hunk 1]
```diff
@@ -738,25 +738,58 @@ impl App {
         persister: &ReceiverPersister,
     ) -> Result<()> {
         // On a session resumption, the receiver will resume again in this state.
+        self.poll_check_payment(proposal, persister).await
```
Comment (DanGould) [inline payjoin-cli/src/app/v2/mod.rs]: one line function implies to me that poll_check_payment and monitor_payjoin_proposal can be combined.

File: payjoin-cli/src/app/v2/mod.rs [hunk 2]
```diff
@@ -738,21 +738,49 @@ impl App {
...
+        loop {
+            // Check if we've exceeded the wait time
+            // since the payment will eventually come through, wondering if i should just remove this check
+            if start.elapsed() >= timeout_duration {
+                return Err(anyhow!(
+                    "Timeout waiting for payment confirmation after {:?}",
+                    timeout_duration
+                ));
+            }
+
```
Comment (spacebear21) [inline payjoin-cli/src/app/v2/mod.rs]: This check is necessary in a production implementation because the payment is not guaranteed to come through if the sender doesn't broadcast it. Instead of erroring out completely we could e.g. prompt the user on whether they want to broadcast the fallback transaction, or wait longer for the payjoin transaction. However we could do this in a follow-up PR after this bug is fixed.

File: payjoin-cli/src/app/v2/mod.rs [hunk 3]
```diff
@@ -738,21 +738,49 @@ impl App {
...
+                        self.wallet()
+                            .is_outpoint_spent(&outpoint)
+                            .map_err(|e| ImplementationError::from(e.into_boxed_dyn_error()))
+                    },
+                )
+                .save(persister);
+
+            match result {
+                Ok(_) => {
+                    println!("Payment confirmed!");
```
Comment (spacebear21) [inline payjoin-cli/src/app/v2/mod.rs]:
```suggestion
                    println!("Payjoin transaction {txid} detected in the mempool!");
```

File: payjoin-cli/src/app/v2/mod.rs [hunk 4]
```diff
@@ -738,21 +738,49 @@ impl App {
...
-                    self.wallet()
-                        .is_outpoint_spent(&outpoint)
-                        .map_err(|e| ImplementationError::from(e.into_boxed_dyn_error()))
-                },
-            )
-            .save(persister)?;
-        Ok(())
+        let poll_interval = tokio::time::Duration::from_millis(200);
+        let timeout_duration = tokio::time::Duration::from_secs(5);
+        let start = tokio::time::Instant::now();
```
Comment (spacebear21) [inline payjoin-cli/src/app/v2/mod.rs]: I think the idiomatic way of doing this would be to use [tokio::time::interval](https://docs.rs/tokio/latest/tokio/time/fn.interval.html) and [tokio::time::timeout](https://docs.rs/tokio/latest/tokio/time/fn.timeout.html#examples).

File: payjoin-cli/src/app/v2/mod.rs [hunk 5]
```diff
@@ -738,21 +738,49 @@ impl App {
...
+                .save(persister);
+
+            match result {
+                Ok(_) => {
+                    println!("Payment confirmed!");
+                    return Ok(());
+                }
+                Err(e) => {
+                    // Log the error but keep polling
+                    tracing::debug!("Payment check failed (will retry): {:?}", e);
```
Comment (spacebear21) [inline payjoin-cli/src/app/v2/mod.rs]: This might result in a lot of redundant debug logs since the polling interval is quite short. I think we can log a "Polling..." debug message before entering the loop and just the outcome after the payment is confirmed or timeout reached.

Comment (zealsham) [reply payjoin-cli/src/app/v2/mod.rs]: Thanks for the review

File: payjoin-cli/src/app/v2/mod.rs (hunk 3 above)
Comment (zealsham) [reply payjoin-cli/src/app/v2/mod.rs]: will a simple "payjoin transaction detected in the mempool"  work ? , getting the txid outside checkpayment function scope will need changes to the api , making private fields public

File: payjoin-cli/src/app/v2/mod.rs [hunk 6]
```diff
@@ -738,21 +738,54 @@ impl App {
...
+                    .save(persister);
+
+                match check_result {
+                    Ok(_) => {
+                        println!("Payjoin transaction detected in the mempool!");
+                        return Ok(());
+                    }
+                    Err(_) => {
+                        // keep polling
+
```
Comment (spacebear21) [inline payjoin-cli/src/app/v2/mod.rs:774]: nit: unnecessary lines
