### PR TITLE
Persist ohttp keys

### LINKED ISSUE #614: Payjoin directory should persist OHTTP keys
Currently it generates new keys on startup, which means anytime the directory server is restarted it produces new OHTTP keys, and any existing payjoin sessions using that directory fail due to " Bad request: Key configuration rejected".

The directory should check if a "ohttp_keys" file exists, and use the existing key configuration if it exists, or generate a new one and save to file otherwise.

Relates to #471

### PR DESCRIPTION
**Pull request by DanGould**
Fix #614

### CODE REVIEW

**Comment by DanGould** [comment]
@spacebear21: @nothingmuch and I paired this, so would you help us out and provide third party review?

File: payjoin-directory/src/key_config.rs [hunk 1]
```diff
@@ -1,19 +1,96 @@
...
+
+impl From<ServerKeyConfig> for ohttp::Server {
+    fn from(value: ServerKeyConfig) -> Self { value.server }
+}
+
+/// Generate a new OHTTP server key configuration
+///
+/// This is combined so that the test path and the prod path both use the same
+/// code. The ServerKeyConfig.ikm is persisted to the configured path, and the
+/// server is used to run the directory server.
```
Comment (spacebear21) [inline payjoin-directory/src/key_config.rs:35]: Duplicated docstring from `pub struct ServerKeyConfig`, I think it's only necessary there.

File: payjoin-directory/src/main.rs [hunk 2]
```diff
@@ -4,10 +4,27 @@ use payjoin_directory::*;
...
     init_logging();
 
+    let key_dir = std::env::var("PJ_OHTTP_KEY_DIR")
+        .map(std::path::PathBuf::from)
+        .unwrap_or_else(|_| std::path::PathBuf::from(DEFAULT_KEY_CONFIG_DIR));
+
+    // Check for generate-key command
+    if let Some(arg) = std::env::args().nth(1) {
+        if arg == "generate-key" {
+            let key_id = std::env::args().nth(2).and_then(|s| s.parse::<u8>().ok()).unwrap_or(1);
```
Comment (spacebear21) [inline payjoin-directory/src/main.rs:20]: It seems unwise to overwrite an existing key if `generate-key` is called without a second argument. We should exit/print a help message if no key ID is passed (and maybe warn if an existing key exists with that ID?)

File: payjoin-directory/src/main.rs [hunk 3]
```diff
@@ -17,7 +34,8 @@ async fn main() -> Result<(), Box<dyn std::error::Error>> {
 
     let db_host = env::var("PJ_DB_HOST").unwrap_or_else(|_| DEFAULT_DB_HOST.to_string());
 
-    payjoin_directory::listen_tcp(dir_port, db_host, timeout).await
+    let ohttp = key_config::read_server_config(&key_dir)?;
```
Comment (spacebear21) [inline payjoin-directory/src/main.rs:37]: If this fails due to no keys existing, can it print a message to guide the user on generating a key?

File: payjoin-directory/src/key_config.rs [hunk 4]
```diff
@@ -1,19 +1,96 @@
...
+        .map_err(|e| anyhow!("Failed to derive OHTTP keys from file: {}", e))?;
+
+    info!("Loaded existing OHTTP Key Configuration from {}", key_path.display());
+    Ok(ServerKeyConfig { ikm, server: ohttp::Server::new(server_config)? })
+}
+
+/// Get the path to the key configuration file
+/// For now, default to [KEY_ID].ikm.
+/// In the future this might be able to save multiple keys named by KeyId.
+fn key_path(dir: &Path) -> PathBuf { dir.join(format!("{}.ikm", KEY_ID)) }
```
Comment (spacebear21) [inline payjoin-directory/src/key_config.rs:80]: Any reason not to have all these functions take a `key` parameter and hardcode KEY_ID in the top-level callsites rather than in here?

File: payjoin-directory/src/main.rs (hunk 3 above)
Comment (DanGould) [reply payjoin-directory/src/main.rs:37]: Because of create_new in `OpenOptions`, no key file is allowed to be overwritten with persist_new_key_config

https://github.com/payjoin/rust-payjoin/pull/616/files#diff-5c409f8306f7fe76f666a34d0a8b323f6c8b602c2519c2342c67cad97227752cR51

File: payjoin-directory/src/key_config.rs (hunk 4 above)
Comment (DanGould) [reply payjoin-directory/src/key_config.rs:80]: We don't actually do any key rotation or have client support for it, so, for now, we're just persisting the one KeyConfiguration as tech debt on purpose to simplify this particular PR

File: payjoin-directory/src/main.rs (hunk 2 above)
Comment (DanGould) [reply payjoin-directory/src/main.rs:20]: Because of [create_new in `OpenOptions`](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.create_new), no key file is allowed to be overwritten with persist_new_key_config

https://github.com/payjoin/rust-payjoin/pull/616/files#diff-5c409f8306f7fe76f666a34d0a8b323f6c8b602c2519c2342c67cad97227752cR51

But I will get rid of .nth(2) logic since it's not used for now

File: payjoin-directory/src/lib.rs [hunk 5]
```diff
@@ -40,16 +40,24 @@ mod db;
 #[cfg(feature = "_danger-local-https")]
 type BoxError = Box<dyn std::error::Error + Send + Sync>;
 
+/// Initialize the OHTTP Key Configuration in memory. For testing purposes.
+pub fn init_ohttp_server() -> Result<ohttp::Server> {
+    let ohttp_config = gen_ohttp_server_config()?;
+    Ok(ohttp_config.into())
+}
+
```
Comment (spacebear21) [inline payjoin-directory/src/lib.rs:48]: This is unused in tests?

**Review by spacebear21 — APPROVED** [review]
utACK 21972aef49d1d7cfd0a70eb4f6dae94584007c5f

Does the Dockerfile need to be updated to generate keys if none exist since they're not made automatically? If it's a required manual step it should be documented somewhere.

File: payjoin-directory/src/main.rs (hunk 3 above)
Comment (DanGould) [reply payjoin-directory/src/main.rs]: no longer having a manual generation function, just generating if the file doesn't exist

File: payjoin-directory/src/lib.rs (hunk 5 above)
Comment (DanGould) [reply payjoin-directory/src/lib.rs]: removed

**Comment by DanGould** [comment]
>  Does the Dockerfile need to be updated to generate keys if none exist since they're not made automatically? If it's a required manual step it should be documented somewhere.

No, and we wouldn't want it to because that's really a docker compose matter. In order to keep the compose functionality working I've changed this to generate on first use and read from the specified or default key configuration directory.

**Review by spacebear21 — APPROVED** [review]
utack c26bea60a49d04d490c900b5ba726c1132473bad
