### PR TITLE
Check for spendable UTXOs before payjoin operations

### LINKED ISSUE #1070: Payjoin-cli should check for spendable utxos before trying to payjoin
Currently if your wallet has no utxos you get: `Error: Obtained failure status(500): Internal Server Error`.
For both send and receive we should provide a more informative error message

### PR DESCRIPTION
**Pull request by 0xZaddyy**
This PR improves error handling when a wallet has no UTXOs.
Previously, attempting to send or receive without UTXOs returned a generic Error: Obtained failure status(500): Internal Server Error.
This change lets the code now performs UTXO checks and provides informative error messages for both send and receive operations.
This makes failures more user-friendly and easier to debug.
Closes #1070 
<details>
  <summary>Pull Request Checklist</summary>

Please confirm the following before requesting review:

- [x] I have [disclosed my use of
  AI](https://github.com/payjoin/rust-payjoin/blob/master/.github/CONTRIBUTING.md#ai-assistance-notice)
  in the body of this PR.
- [x] I have read [CONTRIBUTING.md](https://github.com/payjoin/rust-payjoin/blob/master/.github/CONTRIBUTING.md#commits) and **rebased my branch to produce [hygienic commits](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#committing-patches)**.
</details>

### CODE REVIEW

File: payjoin-cli/src/app/v1.rs [hunk 1]
```diff
@@ -378,6 +378,15 @@ fn try_contributing_inputs(
     let candidate_inputs =
         wallet.list_unspent().map_err(|e| ImplementationError::from(e.into_boxed_dyn_error()))?;
 
+    if candidate_inputs.is_empty() {
+        return Err(ImplementationError::from(
+            anyhow::anyhow!(
+                "No spendable UTXOs available in wallet. Cannot contribute inputs to payjoin."
```
Comment (arminsabouri) [inline payjoin-cli/src/app/v1.rs]: Nit: Lets add a call to action. 

```suggestion
                "No spendable UTXOs available in wallet. Please fund your wallet before resuming this session"
```

This gives the user two thing todo: 
1. Fund the wallet
2. Resume the session

**Review by arminsabouri — COMMENTED** [review]
cACK 

New validation and its use look correct to me. I had one suggestion for the error messages. Lastly, do you mind re-writing your commit message to include the rationale for the change. Not just what changes were made.  

Great work 🔥

File: payjoin-cli/src/app/v2/mod.rs [hunk 2]
```diff
@@ -468,6 +473,12 @@ impl App {
         let wallet = self.wallet();
         let candidate_inputs = wallet.list_unspent()?;
 
+        if candidate_inputs.is_empty() {
+            return Err(anyhow::anyhow!(
+                "No spendable UTXOs available in wallet. Cannot contribute inputs to payjoin."
+            ));
+        }
```
Comment (arminsabouri) [inline payjoin-cli/src/app/v2/mod.rs:480]: This check if fine as the internal error is opaque and this is checked in the input selection logic https://github.com/payjoin/rust-payjoin/blob/3f057e130d45c423a22c5e41007529cc0ee6894f/payjoin/src/core/receive/common/mod.rs#L273C51-L273C87

But ideally the receiver should fallback here instead. And we propogate the internally error somehow so we don't have a duplicate check

File: payjoin-cli/src/app/v1.rs [hunk 3]
```diff
@@ -378,6 +378,15 @@ fn try_contributing_inputs(
     let candidate_inputs =
         wallet.list_unspent().map_err(|e| ImplementationError::from(e.into_boxed_dyn_error()))?;
 
+    if candidate_inputs.is_empty() {
```
Comment (arminsabouri) [inline payjoin-cli/src/app/v1.rs:381]: Same comment as v2 applies here
