### PR TITLE
Resume multiple payjoins

### LINKED ISSUE #205: Construct `Uri` from `Enrolled` method
`Enrolled` should have all of the configuration and state necessary to return a `Uri`. This should enable removal of the less clear `pubkey`, `fallback_target` functions.

This allows `construct_pj_uri` can to be removed from the v2 cli and any similar function from downstream implementation.

Manual construction is particularly annoying because OhttpKeys is required for the enroller and then again for the Uri, and it'd have to be cloned in the Uri without this convenience function.

### LINKED ISSUE #267: V2: Confusing sender/receiver UX flow
Attempting to do a `V2` transaction asynchronously results in some confusing behavior. I may be misunderstanding the intended flow. If I do:

1. `payjoin-cli receive 10000` and wait for the `BIP_21` string
2. Hit `CTRL-C`
3. Run `payjoin-cli send $BIP_21 --fee-rate=2`

I see:

`Sending fallback request to https://pj.bobspacebkk.com/`

Then, after about 30 seconds:

```
Sent fallback transaction
The receiver sent an invalid response: v2 error: Payload too small
Sending fallback request to https://pj.bobspacebkk.com/
```

I see more of the same output after waiting, indicating that the sender is polling the above commands repeatedly. If the receiver comes back online with the `--retry` option, the payjoin completes successfully. However, if after the `Sent fallback transaction` message, you `CTRL-C`, then do `payjoin-cli --retry receive 10000`, I just get a new BIP 21 with a new address. It doesn't seem to acknowledge in any way that I have a session in place and that it retrieved the `Original PSBT` from the sender, modified it, and sent the `Payjoin PSBT` to the directory.

1) This polling from the sender unnecessary to me, unless it is simply to check if the receiver has modified the `Original PSBT`, since the directory is supposed to serve as a buffer and therefore the `Original PSBT` (called `fallback transaction` in `payjoin-cli`). In case this is simply a check for PSBT modification then the terminal output should reflect that with a message like "Checking for receiver PSBT modification..." instead of "Sending fallback transaction" multiple times.

2) It appears that under this scenario, the sender and receiver must be online at the same time during the `Original PSBT` modification by the receiver and while the sender is waiting for the `Payjoin PSBT` to be sent back so the sender broadcast. Interestingly, this mutual liveness requirement appears to be reflected in the final (non-polled) transmissions in the [Payjoin V2 Draft BIP](https://github.com/bitcoin/bips/blob/d7ffad81e605e958dcf7c2ae1f4c797a8631f146/bip-0077.mediawiki#sequence-diagram) (shouldn't the last `Directory -> Sender` transmission containing the `Payjoin PSBT` be polled/retry-able?).

3) The message `The receiver sent an invalid response: v2 error: Payload too small` appears to be a bug? Considering that the payjoin completes successfully if the receiver comes back online during sender polling, payload size doesn't seem to be the issue.

Current UX:
- **Receiver**: `payjoin-cli receive 10000` (outputs BIP 21 string)
- **Receiver**: CTRL-C
- **Sender**: `payjoin-cli send $BIP_21 --fee-rate=2` (wait for `Sent fallback transaction` message)
- **Sender**: CTRL-C
- **Receiver**: `payjoin-cli --retry receive 10000` (Outputs new BIP 21 with same message as before. Does not acknowledge that we're resuming a session).
- **Receiver**: CTRL-C
- **Sender**: `payjoin-cli --retry send $BIP_21 --fee-rate=2` (Outputs `Sending fallback transaction.` Does not acknowledge that we're resuming a session).

Assumed/Ideal UX:
- **Receiver**: `payjoin-cli receive 10000` (outputs BIP 21 string)
- **Receiver**: CTRL-C
- **Sender**: `payjoin-cli send $BIP_21 --fee-rate=2` (wait for `Sent fallback transaction` message)
- **Sender**: CTRL-C
- **Receiver**: `payjoin-cli --retry receive 10000` (Modifies `Original PSBT` to `Payjoin PSBT`, sends to directory with message to user)
- **Receiver**: CTRL-C
- **Sender**: `payjoin-cli --retry send $BIP_21 --fee-rate=2` (Prints message confirming that the `Payjoin PSBT` has been received. Sends payjoin. Prints message saying `Payjoin Received! Tx Id: <TXID>`)

Apologies if I'm just misunderstanding something.

### PR DESCRIPTION
**Pull request by DanGould**
Fix #267 

Send and receive now open sessions with the directory that can be persisted. This includes an e2e test in the UI. As of this PR each session is persisted forever, but a follow up will handle session expiration and archive past sessions for both sender and receiver

This also introduces a new `payjoin-cli resume` command that continues all active send and receive sessions from the database.

## `struct SessionContext`

The `V2Context` has been replaced `SessionContext` that contains an address for the session's URI and an expiry time at which the session is no longer usable.

- [x] Save multiple payjoin send/receive sessions automatically upon send/receive command
- [x] Resume all open send/receive sessions with new resume command 
- [x] send command checks bip21 pj=url against the database, resumes if it exists.
- [x] receive command lists and resumes active sessions and their bip21s
- [x] ensure e2e test runs in CI

Closes #205 as a side effect

### CODE REVIEW

**Comment by DanGould** [comment]
@grizznaut This is not yet quite buttoned up for merge but is ready for a a first pass review. Before it merges I'd like the end-to-end test to run the directory and ohttp relay locally. However I think I will leave session expiration to a follow up PR to be completed by the end of next week for the sake of review simplicity.

File: payjoin-cli/src/app/v2.rs [hunk 1]
```diff
@@ -45,63 +49,82 @@ impl AppTrait for App {
...
+            .header("Content-Type", payjoin::V2_REQ_CONTENT_TYPE)
+            .body(req.body)
+            .send()
+            .await
+            .map_err(map_reqwest_err)?;
+        log::error!("{:?}", ohttp_response.status());
+        let session = initializer
+            .process_res(ohttp_response.bytes().await?.to_vec().as_slice(), ctx)
+            .map_err(|e| anyhow!("Enrollment failed {}", e))?;
+        self.db.insert_recv_session(session.clone())?;
```
Comment (grizznaut) [inline payjoin-cli/src/app/v2.rs:99]: Should it follow the same "get or create session" pattern used in `send_payjoin` here?

File: payjoin-cli/src/app/v2.rs [hunk 2]
```diff
@@ -130,25 +153,30 @@ impl AppTrait for App {
...
-        let pj_receiver_address = self.bitcoind()?.get_new_address(None, None)?.assume_checked();
-        let amount = Amount::from_sat(amount_arg.parse()?);
-        let pj_part = payjoin::Url::parse(fallback_target)
-            .map_err(|e| anyhow!("Failed to parse Payjoin subdirectory target: {}", e))?;
 
-        let pj_uri = PjUriBuilder::new(pj_receiver_address, pj_part, Some(ohttp_keys))
-            .amount(amount)
-            .build();
+    pub async fn resume_payjoins(&self) -> Result<()> {
+        let self_clone = self.clone();
```
Comment (grizznaut) [inline payjoin-cli/src/app/v2.rs:158]: Is this clone necessary? The following should work :

```
        for recv_session in recv_sessions {
            let self_clone = self.clone();
            tasks.push(tokio::task::spawn(async move {
                self_clone.spawn_payjoin_receiver(recv_session, None).await
            }));
        }
```

File: payjoin-cli/src/app/v2.rs [hunk 3]
```diff
@@ -130,25 +153,30 @@ impl AppTrait for App {
...
+        for send_session in send_sessions {
+            let self_clone = self_clone.clone();
+            tasks.push(tokio::task::spawn(async move {
+                self_clone.spawn_payjoin_sender(send_session).await
+            }));
+        }
+        for task in tasks {
+            let _ = task.await?;
+        }
+        println!("All resumed sessions completed.");
```
Comment (grizznaut) [inline payjoin-cli/src/app/v2.rs:178]: It would be helpful to print a "nothing to do" message if there are no sessions to resume.

File: payjoin-cli/src/app/mod.rs [hunk 4]
```diff
@@ -153,13 +147,18 @@ fn http_agent_builder() -> Result<reqwest::ClientBuilder> {
...
     let mut root_cert_store = RootCertStore::empty();
     root_cert_store.add(CertificateDer::from(cert_der.as_slice()))?;
     Ok(reqwest::ClientBuilder::new()
         .danger_accept_invalid_certs(true)
         .use_rustls_tls()
         .add_root_certificate(reqwest::tls::Certificate::from_der(cert_der.as_slice())?))
 }
+
+#[cfg(feature = "danger-local-https")]
+fn read_local_cert() -> Result<Vec<u8>> {
```
Comment (grizznaut) [inline payjoin-cli/src/app/mod.rs:160]: One observation here is that compiling payjoin-cli with `v2` enabled doesn't compile anymore without also including the `danger-local-https` feature:

```
❯ RUST_LOG=debug cargo run --features=v2 -- send --fee-rate=2 $BIP21

error[E0432]: unresolved import `crate::app::read_local_cert`
   --> payjoin-cli/src/app/v2.rs:15:30
    |
15  | use crate::app::{http_agent, read_local_cert};
    |                              ^^^^^^^^^^^^^^^ no `read_local_cert` in `app`
    |
note: found an item that was configured out
   --> payjoin-cli/src/app/mod.rs:160:4
    |
160 | fn read_local_cert() -> Result<Vec<u8>> {
    |    ^^^^^^^^^^^^^^^
    = note: the item is gated behind the `danger-local-https` feature

For more information about this error, try `rustc --explain E0432`.
error: could not compile `payjoin-cli` (bin "payjoin-cli") due to 1 previous error
```

File: payjoin-cli/src/app/v2.rs [hunk 5]
```diff
@@ -45,63 +49,82 @@ impl AppTrait for App {
...
+        println!("Starting new Payjoin session with {}", self.config.pj_directory);
+        let http = http_agent()?;
+        let ohttp_response = http
+            .post(req.url)
+            .header("Content-Type", payjoin::V2_REQ_CONTENT_TYPE)
+            .body(req.body)
+            .send()
+            .await
+            .map_err(map_reqwest_err)?;
+        log::error!("{:?}", ohttp_response.status());
```
Comment (grizznaut) [inline payjoin-cli/src/app/v2.rs:95]: Leftover debug log?

**Review by grizznaut — COMMENTED** [review]
Love the flow for resuming all in-progress sessions without having to supply additional parameters. tACK with some minor comments.

File: payjoin-cli/src/app/mod.rs (hunk 4 above)
Comment (DanGould) [reply payjoin-cli/src/app/mod.rs:160]: Great catch. Thanks for testing so thoughtfully.

**Review by DanGould — COMMENTED** [review]
I believe I have addressed your concerns, and left one comment on the UX design regarding whether or not the `receive` command should resume past sessions.

File: payjoin-cli/src/app/v2.rs (hunk 1 above)
Comment (grizznaut) [reply payjoin-cli/src/app/v2.rs:98]: I didn't have expectations one way or another but was wondering about the different treatment for send vs. receive. This makes sense to me. 

> Perhaps receive should instruct one to use resume when the signal to shut down is given.

Yeah, that sounds nice (same with send if it's still waiting on a response when shut down).

**Review by grizznaut — APPROVED** [review]

**Comment by DanGould** [comment]
I just rebased on master so that tests could run once more
