### PR TITLE
fix(test): remove payjoin-ffi from root CRATES and update ffi test script

### LINKED ISSUE #1454: Allow top level payjoin-ffi testing with ./contrib.test.sh
Because of how our dev shell puts us in the msrv and currently the testing infra in payjoin-ffi prevents the tests being run at the top level when we are in a dev shell it would be nice to fix/allow this behavior for more sweeping testing.
https://github.com/payjoin/rust-payjoin/blob/4186232664b5fc18e9a9999b9c4fa44e3564c506/payjoin-ffi/contrib/test.sh#L1-L10

### PR DESCRIPTION
**Pull request by caarloshenriq**
Closes #1454

payjoin-ffi tests were either being skipped due to an unnecessary MSRV version check or entangling language binding tests with core rust CI.

- Remove payjoin-ffi from CRATES in root contrib/test.sh and contrib/test_local.sh
- Remove MSRV version check from payjoin-ffi/contrib/test.sh
- Add cargo test for payjoin-ffi rust code
- Loop over language bindings (dart, javascript, python) and run their contrib/test.sh

<details>
  <summary>Pull Request Checklist</summary>

Please confirm the following before requesting review:

- [X] I have [disclosed my use of
      AI](https://github.com/payjoin/rust-payjoin/blob/master/.github/CONTRIBUTING.md#ai-assistance-notice)
      in the body of this PR.
- [X] I have read [CONTRIBUTING.md](https://github.com/payjoin/rust-payjoin/blob/master/.github/CONTRIBUTING.md#commits) and **rebased my branch to produce [hygienic commits](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#committing-patches)**.
</details>

### CODE REVIEW

File: payjoin-ffi/contrib/test.sh [hunk 1]
```diff
@@ -1,10 +1,11 @@
...
 
-RUST_VERSION=$(rustc --version | awk '{print $2}')
+cargo test --package payjoin-ffi --verbose --features=_manual-tls,_test-utils
 
-if [[ ! $RUST_VERSION =~ ^1\.85\. ]]; then
-    cargo test --package payjoin-ffi --verbose --features=_manual-tls,_test-utils
-else
-    echo "Skipping payjoin-ffi tests for Rust version $RUST_VERSION (MSRV)"
-fi
+for binding in dart javascript python; do
```
Comment (spacebear21) [inline payjoin-ffi/contrib/test.sh:6]:
```suggestion
BINDINGS="dart javascript python"

for binding in $BINDINGS; do
```

Also we should include c# as well

**Comment by benalleng** [comment]
I think that the `dart/contrib/test.sh` file needs to be given execution permission. I failed to run it from the terminal without a `chmod +x PATH` first.

File: payjoin-ffi/contrib/test.sh (hunk 1 above)
Comment (caarloshenriq) [reply payjoin-ffi/contrib/test.sh]: Applied the suggested change and included csharp in the bindings loop as well

**Comment by caarloshenriq** [comment]
> I think that the `dart/contrib/test.sh` file needs to be given execution permission. I failed to run it from the terminal without a `chmod +x PATH` first.

Fixed, added execution permissions to dart script via `git add --chmod=+x`

**Review by spacebear21 — APPROVED** [review]
ACK da1eacabba5d42c58311ec7c3ab92e950b35fd55

On second thought we could probably parallelize this so it can run on multiple threads instead of blocking on each language? I noticed Claude figured out how to do that on its own when i ask it to run FFI tests, would be nice to formalize that in contrib/test.sh too.

**Comment by caarloshenriq** [comment]
> On second thought we could probably parallelize this so it can run on multiple threads instead of blocking on each language? I noticed Claude figured out how to do that on its own when i ask it to run FFI tests


Nice catch! I’ll look into how Claude approached it and find the best way to formalize that in contrib/test.sh. Should have a PR up by end of the week
