### PR TITLE
Reply json

### LINKED ISSUE #605: Refactor `receive::ReplyableError` for bidirectional conversion across FFI Boundary
We have so far been unable to expose `UncheckedProposal::extract_err_req` and `process_err_res` across the FFI boundary because `ReplyableError` encapsulates internal variants that don't make it across the boundary. Because the internals of the type does not completely convert across the boundary, it cannot be returned back into rust for use in `extract_err_req`, even though `extract_err_req` only relies on `impl JsonError` to extract the error request.

see the issue https://github.com/LtbLightning/payjoin-ffi/issues/59 for details. In summary, we may not want to expose `JsonError` as a public trait because it would allow users to return arbitrary JSON, and leaked data through JSON can be a security vulnerability, e.g. if a receiver returned some internal error message about their wallet state.

The JsonError implementation only maps the error to an error code with a template message. With the exception of the UnknownVersion error, which returns the supported versions, the encapsulated variant tuple contents are not serialized to JSON.

We must figure out some way to cross the foreign language barrier both ways to return these errors to senders for correct operation of the protocol.

### PR DESCRIPTION
**Pull request by DanGould**
Fix #605

### CODE REVIEW

File: payjoin/src/send/error.rs [hunk 1]
```diff
@@ -373,12 +374,12 @@ pub enum WellKnownError {
...
-            WellKnownError::Unavailable(_) => UNAVAILABLE,
-            WellKnownError::NotEnoughMoney(_) => NOT_ENOUGH_MONEY,
-            WellKnownError::VersionUnsupported { .. } => VERSION_UNSUPPORTED,
-            WellKnownError::OriginalPsbtRejected(_) => ORIGINAL_PSBT_REJECTED,
+            WellKnownError::Unavailable(_) => ErrorCode::Unavailable,
+            WellKnownError::NotEnoughMoney(_) => ErrorCode::NotEnoughMoney,
+            WellKnownError::VersionUnsupported { .. } => ErrorCode::VersionUnsupported,
+            WellKnownError::OriginalPsbtRejected(_) => ErrorCode::OriginalPsbtRejected,
         }
     }
```
Comment (spacebear21) [inline payjoin/src/send/error.rs:384]: This makes me wonder if WellKnownError should be something like `pub struct WellKnownError(ErrorCode)` or a struct with `error_code` and `message`?

Comment (DanGould) [reply payjoin/src/send/error.rs]: I was able to net delete some lines in the following commit. Note it also prunes down the `pub` interface of `WellKnownError`, which really should only be exposing its Debug and Display implementations for downstream consumption. No end user/implementor should need to construct this error or pull get the code or message out, Display is the proper interface.

**Review by spacebear21 — APPROVED** [review]
utack 2041f54efb2558c8565266e5dd07847939439217
